// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClC0NxJZnZohmOe-sbV5c1XTbfkv1a6Yw',
    appId: '1:306457939704:web:9942fa80173183e213b50d',
    messagingSenderId: '306457939704',
    projectId: 'simongoterav',
    authDomain: 'simongoterav.firebaseapp.com',
    storageBucket: 'simongoterav.firebasestorage.app',
    measurementId: 'G-JR20JG04BM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt8kGf544FGNoLji8Nqtu6n8uPVhUJi20',
    appId: '1:306457939704:android:15d7ab509d7e380513b50d',
    messagingSenderId: '306457939704',
    projectId: 'simongoterav',
    storageBucket: 'simongoterav.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb34g5Of2b-PfvqZCR2nNamI38B_8_gzs',
    appId: '1:306457939704:ios:3304c6eea23abed913b50d',
    messagingSenderId: '306457939704',
    projectId: 'simongoterav',
    storageBucket: 'simongoterav.firebasestorage.app',
    iosBundleId: 'com.example.mobileDevFinalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCb34g5Of2b-PfvqZCR2nNamI38B_8_gzs',
    appId: '1:306457939704:ios:3304c6eea23abed913b50d',
    messagingSenderId: '306457939704',
    projectId: 'simongoterav',
    storageBucket: 'simongoterav.firebasestorage.app',
    iosBundleId: 'com.example.mobileDevFinalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClC0NxJZnZohmOe-sbV5c1XTbfkv1a6Yw',
    appId: '1:306457939704:web:17b75ffaa150ff5013b50d',
    messagingSenderId: '306457939704',
    projectId: 'simongoterav',
    authDomain: 'simongoterav.firebaseapp.com',
    storageBucket: 'simongoterav.firebasestorage.app',
    measurementId: 'G-69MJN7RCHM',
  );
}
